1 таск
Degior/TODO-list-bot pull request #8
Opened 2023-06-08 14:18 UTC by Degior

2023-06-11 17:08 UTC, vpyzhyanov requested changes
Очень много замечаний по ООП. За ООП пока 0 баллов.

2023-06-11 17:08 UTC, vpyzhyanov commented on src/main/java/org/example/MessageProcessing/Filter.java
> +    public static LocalDate toFilterOutData(String message) throws FilterException {
судя по параметру и возвращаемого значению, выглядит как `parseDate`

2023-06-11 17:08 UTC, vpyzhyanov commented on src/main/java/org/example/MessageProcessing/Filter.java
> +        String[] date;
зачем отделять определения переменных?

2023-06-11 17:08 UTC, vpyzhyanov commented on src/main/java/org/example/MessageProcessing/Filter.java
> +     * Метод преобразует пользовательский ввод даты в более удобный для работы вид
Интересно, у всех методов этого класса абсолютно одинаковое описание, но аргументы и возвращаемые значения разные. Подозреваю попытку всех запутать.

P.S. класс очено сложно написан, явно он гораздо проще, чем выгдядит

2023-06-11 17:08 UTC, vpyzhyanov commented on src/main/java/org/example/MessageProcessing/Filter.java
> +     * @return false, если строка не прошла валидацию
@return должен быть один. Пишите подряд, через запятую.

2023-06-11 17:08 UTC, vpyzhyanov requested changes
Очень много замечаний по ООП. За ООП пока 0 баллов.

2023-06-11 17:15 UTC, vpyzhyanov commented on src/main/java/org/example/Report.java
> +            /openNote (Открыть заметку)
Где редактирование и отметка о выполнении?

2023-06-12 15:24 UTC, mariamarfitcyna commented on src/main/java/org/example/MessageProcessing/MessageHandler.java
> +    private String editNote(Long chatId, String textMsg) {
За это отвечает поле в NoteStorage - currentNote.
При работе с заметкой все действия выполняются с currentNote, чтобы лишний раз не искать нужную заметку по ключам.
Когда работа с заметкой прекращается, currentNote сбрасывается.

2023-06-12 15:49 UTC, mariamarfitcyna commented on src/main/java/org/example/MessageProcessing/MessageHandler.java
> +    private String handle(String textMsg) {
Исправили

2023-06-12 15:50 UTC, mariamarfitcyna commented on src/main/java/org/example/MessageProcessing/MessageHandler.java
> +            case EDITING_NOTE -> toEditNote(chatId, textMsg);
Изменили

2023-06-12 16:01 UTC, mariamarfitcyna commented on src/main/java/org/example/MessageProcessing/MessageHandler.java
> +        } catch (FilterException e) {
Точно, сделали

2023-06-12 16:19 UTC, mariamarfitcyna commented on src/main/java/org/example/MessageProcessing/MessageHandlerState.java
> +    PROCESSING_EDITING_NOTE,
EDITING_NOTE - пользователь отправляет комманду "/Редактировать заметку"
PROCESSING_EDITING_NOTE - пользователь указывает дату заметки и то, какое именно изменение заметки он хочет осуществить: удаление, выполнение задачи, добавление задачи.

2023-06-12 16:21 UTC, mariamarfitcyna commented on src/main/java/org/example/MessageProcessing/MessageHandler.java
> +    private String editNote(Long chatId, String textMsg) {
прочитала ниже комментарий про многопоточную среду, осознала

2023-06-12 16:21 UTC, mariamarfitcyna commented on src/main/java/org/example/NoteStrusture/NoteStorage.java
> +    private Note currentNote;
поняли, спасибо
изменим

2023-06-17 08:35 UTC, mariamarfitcyna commented on src/main/java/org/example/App.java
> +        telegram.onUpdateReceived();
исправлено

2023-06-17 08:36 UTC, mariamarfitcyna commented on src/main/java/org/example/MessageProcessing/Filter.java
> +public class Filter {
изменили название и добавили javaDoc

2023-06-17 08:36 UTC, mariamarfitcyna commented on src/main/java/org/example/MessageProcessing/Filter.java
> +     * Метод преобразует пользовательский ввод даты в более удобный для работы вид
изменили название и добавили javaDoc

2023-06-17 08:36 UTC, mariamarfitcyna commented on src/main/java/org/example/MessageProcessing/Filter.java
> +    public static LocalDate toFilterOutData(String message) throws FilterException {
точно, исправили

2023-06-17 08:39 UTC, mariamarfitcyna commented on src/main/java/org/example/MessageProcessing/Filter.java
> +        String[] date;
это осталось от предыдущей логики, а изменить забыла

2023-06-17 08:40 UTC, mariamarfitcyna commented on src/main/java/org/example/MessageProcessing/Filter.java
> +     * Метод преобразует пользовательский ввод даты в более удобный для работы вид
сделали попроще

2023-06-17 08:40 UTC, mariamarfitcyna commented on src/main/java/org/example/MessageProcessing/Filter.java
> +     * @return false, если строка не прошла валидацию
хорошо, поменяли

2023-06-17 08:43 UTC, mariamarfitcyna commented on src/main/java/org/example/MessageProcessing/MessageHandler.java
> +            case CREATING_NOTE_DATE -> appendNote(chatId, textMsg);
исправлено

2023-06-18 13:58 UTC, mariamarfitcyna commented on src/main/java/org/example/NoteStrusture/NoteStorage.java
> +        return null;
исправлено

2023-06-18 13:59 UTC, mariamarfitcyna commented on src/main/java/org/example/NoteStrusture/Task.java
> +    private TaskState state;
точно, исправили
раньше инициализировали в конструкторе, потом его изменили, и забыли

2023-06-18 17:00 UTC, mariamarfitcyna commented on src/main/java/org/example/MessageProcessing/FilterException.java
> +public class FilterException extends Exception {
теперь на месте

2023-06-18 17:00 UTC, mariamarfitcyna commented on src/main/java/org/example/MessageProcessing/FormatterException.java
> +public class FormatterException extends Exception {
теперь на месте

2023-06-18 17:00 UTC, mariamarfitcyna commented on src/main/java/org/example/MessageProcessing/MessageHandler.java
> + * Класс MessageHandler. Отвечает за логику работы программы.
действительно, теперь там соответствующее описание

2023-06-18 17:00 UTC, mariamarfitcyna commented on src/main/java/org/example/MessageProcessing/MessageHandler.java
> +
исправлено)

2023-06-18 17:00 UTC, mariamarfitcyna commented on src/main/java/org/example/MessageProcessing/MessageHandler.java
> +    private String getNonSpecialCommand(Long chatId, String textMsg) {
исправлено

2023-06-18 17:01 UTC, mariamarfitcyna commented on src/main/java/org/example/MessageProcessing/MessageHandler.java
> +            messageHandlerState = MessageHandlerState.PROCESSING_EDITING_NOTE;
поняли, добавили hashMap таких состояний

2023-06-18 17:01 UTC, mariamarfitcyna commented on src/main/java/org/example/MessageProcessing/MessageHandler.java
> +            Note note = noteStorage.getNote(chatId, Filter.toFilterOutData(textMsg));
теперь это Parser

2023-06-18 17:01 UTC, mariamarfitcyna commented on src/main/java/org/example/MessageProcessing/MessageHandler.java
> +            //return notesLogic.getNote(chatId, Filter.toFilterOutData(textMsg)) + Report.NOTE_EDITING;
готово

2023-06-18 17:03 UTC, mariamarfitcyna commented on src/main/java/org/example/MessageProcessing/MessageHandler.java
> +    private String toLookForNote(Long chatId, String message) {
почему-то на ум фразовый глагол пришел, теперь это search

2023-06-18 17:03 UTC, mariamarfitcyna commented on src/main/java/org/example/MessageProcessing/MessageHandler.java
> +    private String toDeleteNote(Long chatId, String message) {
хорошо

2023-06-18 17:06 UTC, mariamarfitcyna commented on src/main/java/org/example/NoteStrusture/NoteStorage.java
> +    private final Map<Long, Map<LocalDate, Note>> allNotes;
хорошо, написали

2023-06-18 17:06 UTC, mariamarfitcyna commented on src/main/java/org/example/NoteStrusture/NoteStorage.java
> +        if (allNotes.containsKey(chatId)) {
точно!
спасибо, исправила этот и еще несколько методов

2023-06-18 17:06 UTC, mariamarfitcyna commented on src/main/java/org/example/NoteStrusture/NoteStorage.java
> +            allNotes.get(chatId).put(localDate, new Note());
сейчас тоже не понимаю, изменила логику работы метода

2023-06-18 17:07 UTC, mariamarfitcyna commented on src/main/java/org/example/NoteStrusture/NoteStorage.java
> +    public void addTaskToNote(String tasks) {
Иправили

2023-06-18 17:07 UTC, mariamarfitcyna commented on src/main/java/org/example/NoteStrusture/NoteStorage.java
> +     * Метод возвращающий список всех заметок пользователя
Исправили

2023-06-18 17:07 UTC, mariamarfitcyna commented on src/main/java/org/example/NoteStrusture/NoteStorage.java
> +
исправили

2023-06-18 17:08 UTC, mariamarfitcyna commented on src/main/java/org/example/NoteStrusture/NoteStorage.java
> +        return null;
исправлено

2023-06-18 17:08 UTC, mariamarfitcyna commented on src/main/java/org/example/NoteStrusture/NoteStorage.java
> +
исправлено

2023-06-18 17:08 UTC, mariamarfitcyna commented on src/main/java/org/example/NoteStrusture/Task.java
> +    public void chahgeState() {
исправили

2023-06-18 17:09 UTC, mariamarfitcyna commented on src/main/java/org/example/Report.java
> +public class Report {
исправлено

2023-06-18 17:09 UTC, mariamarfitcyna commented on src/main/java/org/example/Report.java
> +            /openNote (Открыть заметку)
добавили

2023-06-20 18:32 UTC, Degior commented on src/test/java/org/example/MessafeProcessingTests/MessageHandlerTest.java
> +    void processInputWithStartCommandShouldReturnStartMessage() {
убрано

2023-06-20 18:32 UTC, Degior commented on src/test/java/org/example/MessafeProcessingTests/MessageHandlerTest.java
> +    public void processInput_NonStartCommand_ReturnsStartMessage() {
убрано

2023-06-20 18:32 UTC, Degior commented on src/test/java/org/example/MessafeProcessingTests/MessageHandlerTest.java
> +    void processInputWithHelpCommandShouldReturnHelpMessage() {
убрано

2023-06-20 18:32 UTC, Degior commented on src/test/java/org/example/MessafeProcessingTests/MessageHandlerTest.java
> +    void processInputWithUnknownCommandShouldReturnDefaultMessage() {
Добавлен JavaDoc

2023-06-20 18:33 UTC, Degior commented on src/test/java/org/example/MessafeProcessingTests/MessageHandlerTest.java
> +        assertEquals("Теперь можешь внести в план на день несколько задач через Enter. \n", result);
Добавлена проверка на то создается ли что либо и на корректность добавления

2023-06-20 18:33 UTC, Degior commented on src/test/java/org/example/MessafeProcessingTests/MessageHandlerTest.java
> +        assertEquals("Теперь можешь внести в план на день несколько задач через Enter. \n", result);
убран

2023-06-20 18:33 UTC, Degior commented on src/test/java/org/example/MessafeProcessingTests/MessageHandlerTest.java
> +        String noteMessage = "12.12.2020";
Учтено

2023-06-20 18:33 UTC, Degior commented on src/test/java/org/example/MessafeProcessingTests/MessageHandlerTest.java
> +        String noteMessage = "12.12";
Теперь больше одного раза

2023-06-20 18:33 UTC, Degior commented on src/test/java/org/example/MessafeProcessingTests/MessageHandlerTest.java
> +        assertEquals("Заметка удалена", result);
Теперь проверяем

2023-06-20 18:33 UTC, Degior commented on src/test/java/org/example/MessafeProcessingTests/MessageHandlerTest.java
> +    public void OpenNoteTest(){
Исправлено

2023-06-20 18:33 UTC, Degior commented on src/test/java/org/example/MessafeProcessingTests/MessageHandlerTest.java
> +        assertEquals("1. купить цветов\n2. украсить дом\n",  messageHandler.processInput(1l, noteMessage));
Поменяли на указанную реализацию

2023-06-20 18:33 UTC, Degior commented on src/test/java/org/example/MessafeProcessingTests/MessageHandlerTest.java
> +}
Добавлены необходимые тесты

2023-06-20 18:33 UTC, Degior commented on src/main/java/org/example/Telegram/Telegram.java
> +        Scanner scanner = new Scanner(System.in);
Поменяли название на более логичное

2023-06-20 18:34 UTC, Degior commented on src/main/java/org/example/Telegram/Telegram.java
> +        while (true) {
Мы же тут симулируем работу телеграмма с пользователями. Пользователь не должен уметь выключать бота. Так что не совсем понятно как это сделать и нужно ли

2023-06-20 18:35 UTC, Degior commented on src/main/java/org/example/Telegram/Telegram.java
> +        Scanner scanner = new Scanner(System.in);
Мы же тут симулируем работу телеграмма с пользователями. Пользователь должен уметь написать когда угодно. Так что не совсем понятно как это сделать и нужно ли

2023-06-20 18:35 UTC, Degior commented on src/main/java/org/example/Telegram/Telegram.java
> +     * @param message
Исправлено

2023-06-20 18:35 UTC, Degior commented on src/main/java/org/example/Telegram/Telegram.java
> + * Класс отвечающей за работу Telegram. Пока не реализован.
Исправлено

2023-06-20 19:05 UTC, Degior commented on src/main/java/org/example/Report.java
> +package org.example;
Перенесли

2023-06-20 19:05 UTC, Degior commented on src/main/java/org/example/Report.java
> +            """; // Стартовое сообщение
Добавили JavaDoc

2023-06-20 19:08 UTC, Degior commented on src/main/java/org/example/MessageProcessing/MessageHandlerState.java
> +public enum MessageHandlerState {
Добавили

2023-06-22 09:27 UTC, mariamarfitcyna commented on src/main/java/org/example/NoteStrusture/TaskStatus.java
> + * Класс для описания важности задачи (пока не используется)
убрали

2023-06-22 09:29 UTC, mariamarfitcyna commented on src/test/java/org/example/NoteStructureTests/NoteStorageTest.java
> +    NoteStorage noteStorage;
дабавлены

2023-06-22 14:27 UTC, mariamarfitcyna commented on src/test/java/org/example/NoteStructureTests/NoteStorageTest.java
> +    public void appendNoteWithException(){
добавлен

2023-06-22 14:35 UTC, mariamarfitcyna commented on src/test/java/org/example/NoteStructureTests/NoteStorageTest.java
> +        Assertions.assertEquals("1. новая задача\n", NoteFormatter.getNoteText(noteStorage.getNote(chatId, localDate)));
поняла, исправила

2023-06-23 10:35 UTC, mariamarfitcyna commented on src/test/java/org/example/NoteStructureTests/NoteTest.java
> +    public void getTextTask2(){
точно, поняла

2023-06-23 11:51 UTC, mariamarfitcyna commented on src/main/java/org/example/NoteStrusture/NoteStorage.java
> +    public void resetNote() {
исправили, добавив в NoteStorage еще один метод

2023-07-18 10:07 UTC, closed without merging